FROM node:14

# 安装jdk11
WORKDIR /usr/local/java
# # 拷贝安装包到jdk路径（会自动解压）
RUN wget -P /usr/local/java http://115.231.255.14:81/download/jdk-11.0.10_linux-x64_bin.tar.gz
RUN tar -zxvf jdk-11.0.10_linux-x64_bin.tar.gz 
# 创建symbol link
RUN ln -s /usr/local/java/jdk-11.0.10 /usr/local/java/jdk
# 生成jre
RUN jdk/bin/jlink --module-path jmods --add-modules java.desktop --output ./jdk/jre
# 设置环境变量
ENV JAVA_HOME /usr/local/java/jdk
ENV JRE_HOME ${JAVA_HOME}/jre
ENV CLASSPATH .:${JAVA_HOME}/lib:${JRE_HOME}/lib
ENV PATH ${JAVA_HOME}/bin:$PATH
RUN rm -rf ./jdk-11.0.10_linux-x64_bin.tar.gz

# 安装go
WORKDIR /usr/local/go
RUN mkdir tmp 1.11 1.12
RUN wget -P ./tmp https://dl.google.com/go/go1.11.5.linux-amd64.tar.gz & wget -P ./tmp https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
RUN tar -zxvf ./tmp/go1.11.5.linux-amd64.tar.gz  -C ./1.11 & tar -zxvf ./tmp/go1.12.7.linux-amd64.tar.gz -C ./1.12
RUN rm -rf ./tmp

# 工作目录
WORKDIR /usr/src/app
# package.json到项目目录
COPY package.json ./
# 安装npm依赖
RUN npm install --silent --no-cache --registry=https://registry.npm.taobao.org
# 拷贝整个目录
COPY ./ ./
# 暴露端口
EXPOSE 4000 9229

CMD ["npm", "run", "start:debug"]