version: "3.5"

services:
    compile-service-prod:
        ports:
            - 4000:4000
        build: 
            context: ../
            dockerfile: Dockerfile
        container_name: 'compile-service-prod'
        volumes: 
            - ../src:/usr/src/app/src
            - ../dist:/usr/src/app/dist